// Protocol Findings — Context-based analysis of 537 flagged protocols
// Generated 2026-02-20 by manual review (not keyword scanning)
// 23 real findings from 537 flagged protocols (4.3% hit rate, confirming 60-100% FP rate of keyword scanning)

const PROTOCOL_FINDINGS = {
  meta: {
    total_protocols_reviewed: 537,
    total_findings: 23,
    hit_rate: "4.3%",
    method: "context_analysis",
    date: "2026-02-20",
    cities_with_findings: 5,
    cities_without_findings: 10
  },
  findings: [
    // ═══ HAIFA (5 findings) ═══
    {
      id: "haifa-1",
      proposer_key: "lazimi",
      city: "HAIFA",
      city_he: "חיפה",
      index: 359,
      date: "2020-09-08",
      document: "תקציר ישיבת מועצה 08.09.2020",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "approved",
      outcome_he: "אושר בהצבעה",
      summary_he: "מועצת העיר חיפה אישרה בהצבעה תוכנית עירונית כוללת לעיר רגישה מגדרית. הוועדה לשוויון מגדרי קיבלה סמכות לייצר מסמכי עבודה, שיתופי פעולה עם ועדות הרשות, ועדכון מדיניות. חיפה הוגדרה כ\"מובילת הדרך\" בקידום ערים רגישות מגדרית בישראל.",
      summary_en: "Haifa city council approved a comprehensive gender-sensitive city plan. The Gender Equality Committee was empowered to create policy documents, coordinate with all municipal committees, and update policies. Haifa positioned as national leader in gender-sensitive cities.",
      quote_he: "תחת הועדה לשוויון מגדרי, תתן מועצת העיר את הסמכות לוועדה לייצר מסמכי עבודה מסודרים בנושא, לשם יצירת פלטפורמות עבודה מול גורמי הרשות, שיתופי פעולה עם הועדות השונות ברשות, עדכון מדיניות ויישום ניירות עמדה [...] על חיפה להיות מובילת הדרך בעידוד וקידום יצירת ערים רגישות מגדרית בישראל, להיות חוד החנית בכנסים ארציים, מול משרדי ממשלה ועשיה משותפת למען חקיקה ושינוי מדיניות ארצית בנושאים אלו.",
      proposer: "נעמה לזימי, חברת מועצת העירייה",
      source_url: "https://www.haifa.muni.il/city-and-muni/city-council/protocols/"
    },
    {
      id: "haifa-2",
      proposer_key: null,
      city: "HAIFA",
      city_he: "חיפה",
      index: 727,
      date: null,
      document: "קריטריוני מימון עירוני לארגונים",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "policy",
      outcome_he: "מדיניות פעילה",
      summary_he: "קריטריוני מימון עירוניים לארגונים כוללים דרישת קידום שוויון מגדרי, כולל ארגוני להט\"ב. תנאי סף לקבלת תמיכה עירונית.",
      summary_en: "Municipal funding criteria for organizations include gender equality requirements, including LGBTQ+ organizations. Prerequisite for receiving municipal support.",
      quote_he: "קידום שוויון מגדרי כתנאי לתמיכה עירונית — כולל ארגוני להט\"ב",
      source_url: "https://www.haifa.muni.il/city-and-muni/city-council/protocols/"
    },
    {
      id: "haifa-3",
      proposer_key: null,
      city: "HAIFA",
      city_he: "חיפה",
      index: 812,
      date: "2018",
      document: "הסכם קואליציוני חיים-בחיפה ומרצ",
      category: "coalition_agreement",
      category_he: "הסכם קואליציוני",
      outcome: "signed",
      outcome_he: "נחתם",
      summary_he: "הסכם קואליציוני בין \"חיים בחיפה\" (עינת קליש-רותם) לסיעת מרצ כולל במפורש \"קידום שיוויון מגדרי\" כיעד מדיניות יסודי של הקואליציה.",
      summary_en: "Coalition agreement between 'Haim BaHaifa' (Einat Kalish-Rotem) and Meretz explicitly includes 'gender equality promotion' as a foundational policy goal.",
      quote_he: "שתי הסיעות מבקשות לקדם נושאים מוניציפליים כגון: [...] קידום שיוויון מגדרי, קידום ההעסקה הישירה במוסדות העירייה",
      source_url: "https://www.haifa.muni.il/city-and-muni/city-council/protocols/"
    },
    {
      id: "haifa-4",
      proposer_key: null,
      city: "HAIFA",
      city_he: "חיפה",
      index: 606,
      date: "2014-02-04",
      document: "תקציר ישיבת מועצה 04.02.2014",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "established",
      outcome_he: "הוקמה",
      summary_he: "ראש העיר מינה את פרופ' גדי לנדאו לעמוד בראשות ועדה ציבורית לקהילת הלהט\"ב — חינוך, רווחה, תרבות, פנאי, ובניית קו פתוח בין גורמי העירייה לקהילה.",
      summary_en: "Mayor appointed Prof. Gadi Landau to head a public committee for LGBTQ+ community needs — education, welfare, culture, leisure, and building an open channel between municipal bodies and the community.",
      quote_he: "לפני מספר חודשים מינה ראש העיר את פרופ' גדי לנדאו לעמוד בראשות ועדה ציבורית שתבחן תחומים רחבים הנוגעים לקהילת הלהט\"ב ולצרכיה, חינוך, רווחה, תרבות, פעילות פנאי, בניית קו פתוח ונגיש בין גורמי העירייה להורים לחברי הקהילה, ובעצם לכל דבר ועניין.",
      source_url: "https://www.haifa.muni.il/city-and-muni/city-council/protocols/"
    },
    {
      id: "haifa-5",
      proposer_key: null,
      city: "HAIFA",
      city_he: "חיפה",
      index: 590,
      date: "2014-09-02",
      document: "תקציר ישיבת מועצה 02.09.2014",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "appointed",
      outcome_he: "מינוי",
      summary_he: "ביאטריס רוזן כץ נבחרה במכרז לתפקיד יועצת ראש העיר למעמד האישה. בפרוטוקולים מ-2017 והלאה התפקיד שונה ל\"יועצת ראש העיר לשוויון מגדרי\" — שינוי מ\"מעמד האישה\" ל\"שוויון מגדרי\".",
      summary_en: "Beatrice Rosen Katz appointed as mayor's advisor on women's status. By 2017, the role was rebranded to 'advisor on gender equality' — a shift from women's status to gender equality framing.",
      quote_he: "גב' ביאטריס רוזן כץ, נבחרה במכרז לתפקיד יועצת ראש העיר למעמד האישה.",
      source_url: "https://www.haifa.muni.il/city-and-muni/city-council/protocols/"
    },

    // ═══ HERZLIYA (7 findings) ═══
    {
      id: "herzliya-1",
      proposer_key: "padlon",
      city: "HERZLIYA",
      city_he: "הרצליה",
      index: 195,
      date: "2022-12-27",
      document: "פרוטוקול דיונים נגיש, פ\"כ מס' 71, ישיבת מועצה מן המניין",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "declaration",
      outcome_he: "הצהרת ראש העיר",
      summary_he: "ראש העיר פדלון הצהיר בישיבת מועצה שעיריית הרצליה לא תעניק רישיון עסק לבתי עסק המפלים על רקע דת, גזע, מין או נטייה מינית. הצהרה על המשך חינוך לפלורליזם — מוצגת כהתנגדות למדיניות ממשלה.",
      summary_en: "Mayor Padlon declared Herzliya will not grant business licenses to businesses discriminating based on religion, race, sex, or sexual orientation. Framed as opposition to national government policy.",
      quote_he: "עיריית הרצליה מסמנת כאן הערב קו אדום חד וברור — כאן בהרצליה אין ולא יהיה מקום לאפליה, לגזענות ולשנאת חינם. [...] העירייה לא תעניק רישיון עסק לבתי עסק בעיר ומסחר בעיר אשר יפלו אנשים על רקע דת, גזע, מין או נטייה מינית.",
      proposer: "ראש העיר משה פדלון",
      source_url: "https://www.herzliya.muni.il/protocols/"
    },
    {
      id: "herzliya-2",
      proposer_key: null,
      city: "HERZLIYA",
      city_he: "הרצליה",
      index: 194,
      date: "2022-12-27",
      document: "סדר יום, ישיבת מועצה מן המניין",
      category: "education_program",
      category_he: "תוכנית חינוך",
      outcome: "confirmed",
      outcome_he: "אושר תקציבית",
      summary_he: "מנהל אגף החינוך אישר שהעירייה ערוכה תקציבית להמשך מימון תוכניות ליברליות (אזרחות, דמוקרטיה, שוויון מגדרי, מאבק בגזענות, מיניות בריאה) מתקציבים עירוניים, גם אם תוכנית גפ\"ן הלאומית תעבור לשליטה שמרנית.",
      summary_en: "Education department confirmed municipal budget to continue funding liberal programs (citizenship, democracy, gender equality, anti-racism, sexual health education) from municipal funds, even if national GaFaN program is taken over by conservative forces.",
      quote_he: "נעננו כי האגף ערוך תקציבית להמשך מימון כל פעילות התואמת את המתואר לעיל באמצעות תקציבים עירוניים, וכי אף תכנית ליברלית לא תופסק בשל העדר תקציב.",
      proposer: "סיעות יש עתיד והחופש לבחור",
      source_url: "https://www.herzliya.muni.il/protocols/"
    },
    {
      id: "herzliya-3",
      proposer_key: "oren_yanai",
      city: "HERZLIYA",
      city_he: "הרצליה",
      index: 252,
      date: "2022-03-15",
      document: "סדר יום, ישיבת מועצה מן המניין",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "proposal",
      outcome_he: "הצעה (ללא הצבעה נראית)",
      summary_he: "הצעה לאמץ את הדו\"ח הממשלתי למאבק בהדרת נשים כמדיניות עירונית מחייבת. הגדרת הפרדה מגדרית כאפליה שיש להילחם בה במרחב הציבורי.",
      summary_en: "Proposal to adopt the government report on combating exclusion of women as binding municipal policy. Defines gender separation as discrimination to be fought in public space.",
      quote_he: "הצעה לסדר [...] בנושא: אימוץ הדו\"ח הממשלתי למאבק בהדרת נשים כמדיניות מחייבת. הדרת נשים במרחב הציבורי היא תופעה חמורה המתגברת [...] הפרדה מגדרית היא אחת מצורות הדרת הנשים הנפוצות ביותר בישראל.",
      proposer: "דנה אורן ינאי",
      source_url: "https://www.herzliya.muni.il/protocols/"
    },
    {
      id: "herzliya-4",
      proposer_key: "fabian",
      city: "HERZLIYA",
      city_he: "הרצליה",
      index: 327,
      date: "2020-12-22",
      document: "פרוטוקול דיונים נגיש, פ\"כ מס' 36, ישיבת מועצה מן המניין",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "proposal",
      outcome_he: "הצעה (ללא הצבעה נראית)",
      summary_he: "הצעה לתקצוב מגדרי: לפחות 50% נשים בדירקטוריונים של חברות עירוניות, מדדים מגדריים לבחינת פעילות העירייה, פילוח תקציב בראיה מגדרית, דו\"ח שנתי על השפעת החלטות על נשים.",
      summary_en: "Proposal for gender budgeting: 50% women on municipal corporate boards, gender metrics for municipal activities, gender-disaggregated budget analysis, annual gender impact report.",
      quote_he: "לוודא שיש לפחות 50 אחוז נשים בדירקטוריונים של החברות העירונית. צורך בקיום מדדים מגדריים הבוחנים את פעילות העירייה בראיה מגדרית. פילוח תקציב העירייה בראיה מגדרית — קיום דו\"ח שנתי המגדיר כיצד משפיעות כל החלטות העירייה על הנשים בעיר.",
      proposer: "חבר מועצה פביאן",
      source_url: "https://www.herzliya.muni.il/protocols/"
    },
    {
      id: "herzliya-5",
      proposer_key: "padlon",
      city: "HERZLIYA",
      city_he: "הרצליה",
      index: 236,
      date: "2022-06-28",
      document: "פרוטוקול דיונים נגיש, פ\"כ מס' 60, ישיבת מועצה מן המניין",
      category: "education_program",
      category_he: "תוכנית חינוך",
      outcome: "declaration",
      outcome_he: "הצהרת ראש העיר",
      summary_he: "ראש העיר פדלון תמך פומבית בתהליך שינוי זהות מגדרית של תלמיד כיתה ב' בבית ספר יסודי. גינה חבר מועצה שהתנגד ל\"מפגש שיתוף\" שנערך בנושא. הצהיר שהעירייה תמשיך לפעול על פי ערכי שוויון, הכלה וסובלנות בנוגע לזהות מגדרית.",
      summary_en: "Mayor Padlon publicly backed a school's facilitation of a gender identity transition for a 2nd-grader. Rebuked a council member who criticized the 'sharing session' held about it. Declared the municipality will continue acting on values of equality and inclusion regarding gender identity.",
      quote_he: "בעיר דמוקרטית הדוגלת בשוויון, הכלה וסובלנות, לא יהיה מקום לאמירות פוגעניות ולא נסכים לקבלן. העירייה תמשיך לתמוך ולפעול על פי ערכים של שוויון, הכלה, סובלנות וכבוד כלפי כל אדם באשר הוא.",
      proposer: "ראש העיר משה פדלון",
      source_url: "https://www.herzliya.muni.il/protocols/"
    },
    {
      id: "herzliya-6",
      proposer_key: null,
      city: "HERZLIYA",
      city_he: "הרצליה",
      index: 32,
      date: "2025-11-18",
      document: "סדר יום + פרוטוקול, ישיבת מועצה מן המניין",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "agenda",
      outcome_he: "סעיף בסדר יום",
      summary_he: "מינוי יועצת לקידום מעמד האישה כסעיף בסדר יום ישיבת המועצה. ממשיך מסורת של \"מנהל נשים\" ו\"יועצת ראש העיר לקידום מעמד האישה\" הפועלים בעיר.",
      summary_en: "Appointment of Women's Status Advisor as council agenda item. Continues the tradition of a Women's Administration and mayor's advisor role operating in the city.",
      quote_he: "11. מינוי יועצת לקידום מעמד האישה",
      source_url: "https://www.herzliya.muni.il/protocols/"
    },
    {
      id: "herzliya-7",
      proposer_key: null,
      city: "HERZLIYA",
      city_he: "הרצליה",
      index: 17,
      date: null,
      document: "עלון מידע — עמותת תהל\"ה",
      category: "org_partnership",
      category_he: "שיתוף פעולה עם ארגון",
      outcome: "active",
      outcome_he: "שיתוף פעולה פעיל",
      summary_he: "עמותת תהל\"ה (תמיכת הורים להורים של ילדים מהקהילה הלהט\"בית) מפעילה קבוצת תמיכה במרכז הבריאות העירוני, בשיתוף מחלקת הבריאות העירונית של עיריית הרצליה.",
      summary_en: "TEHILA (LGBTQ+ parent support org) runs monthly support groups at the Municipal Health Center, in partnership with Herzliya's Municipal Health Department.",
      quote_he: "עמותת תהל\"ה מפעילה קבוצת תמיכה, העצמה וידע להורים לילדים מהקהילה הגאה בעיר הרצליה, בשיתוף עם עיריית הרצליה — מחלקת הבריאות העירונית.",
      source_url: "https://www.herzliya.muni.il/protocols/"
    },

    // ═══ GIVATAYIM (5 findings) ═══
    {
      id: "givatayim-1",
      proposer_key: "kaplan",
      city: "GIVATAYIM",
      city_he: "גבעתיים",
      index: 169,
      date: "2023-07-05",
      document: "פרוטוקול נגיש, ישיבת מועצה מספר 69",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "approved",
      outcome_he: "אושר פה אחד",
      summary_he: "המועצה אישרה פה אחד מדיניות של שוויון מגדרי בייצוג באירועי תרבות, אמנות, חינוך והעשרה עירוניים.",
      summary_en: "Council unanimously approved mandatory gender equality in representation at all municipal culture, arts, education and enrichment events.",
      quote_he: "הצעה לסדר מאת חבר המועצה, מר רונאן קפלן, בנושא ייצוג נשים בפעילויות תרבות, אמנות, חינוך והעשרה בגבעתיים. הצבעה: פה אחד. החלטה: באירועים העירוניים יהיה שיויון מגדרי ככל שניתן.",
      proposer: "רונאן קפלן, חבר המועצה",
      source_url: "https://www.givatayim.muni.il/protocols/"
    },
    {
      id: "givatayim-2",
      proposer_key: "wolfson",
      city: "GIVATAYIM",
      city_he: "גבעתיים",
      index: 492,
      date: "2019-05-15",
      document: "פרוטוקול נגיש, ישיבת מועצה מספר 8",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "rejected",
      outcome_he: "נדחה 9-4",
      summary_he: "הצעה להקמת ועדה עירונית לשוויון מגדרי נדחתה ברוב של 9 נגד 4 בעד. העירייה טענה שהנושא כבר מטופל היטב על ידי סגנית ראש העירייה.",
      summary_en: "Proposal to establish a formal municipal gender equality committee was REJECTED 9-4. The city stated the issue is already well-handled by the deputy mayor.",
      quote_he: "הצעה לסדר מאת גב' ויוי וולפסון: הקמת ועדה לקידום שוויון מגדרי. [...] אני מבקשת מראש העירייה להקים ועדה עירונית לשוויון מגדרי דומה לשאר הועדות [...] הצבעה 9 נגד [...] 4 בעד [...] החלטה כל נושא השוויון המגדרי מטופל בתקופה האחרונה באופן מצוין.",
      proposer: "ויוי וולפסון",
      source_url: "https://www.givatayim.muni.il/protocols/"
    },
    {
      id: "givatayim-3",
      proposer_key: "kaplan",
      city: "GIVATAYIM",
      city_he: "גבעתיים",
      index: 210,
      date: "2022-12-07",
      document: "פרוטוקול נגיש, ישיבת מועצה מספר 62",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "removed",
      outcome_he: "הורד מסדר היום 11-4",
      summary_he: "הצעה בנושא \"הפרדה מגדרית\" הורדה מסדר היום בהצבעה של 11 בעד הסרה, 4 נגד. המועצה סירבה לדון בנושא כלל.",
      summary_en: "Proposal about 'gender separation' was voted off the agenda 11-4. Council refused to discuss the topic entirely.",
      quote_he: "הצעה לסדר מאת חבר המועצה, רונאן קפלן, בנושא הפרדה מגדרית. הצבעה על הורדת הסעיף מסדר היום: 11 בעד [...] 4 נגד [...] החלטה הצעה לסדר של חבר המועצה רונאן קפלן ירדה מסדר היום, ברוב קולות.",
      proposer: "רונאן קפלן, חבר המועצה",
      source_url: "https://www.givatayim.muni.il/protocols/"
    },
    {
      id: "givatayim-4",
      proposer_key: "koren",
      city: "GIVATAYIM",
      city_he: "גבעתיים",
      index: 31,
      date: "2025-09-03",
      document: "סדר יום, ישיבת מועצה מספר 26",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "agenda",
      outcome_he: "סעיף בסדר יום",
      summary_he: "הצעה לשוויון מגדרי (50/50) בתעודות ופרסי הוקרה עירוניים. הצעה בלבד — תוצאת ההצבעה לא נראית.",
      summary_en: "Proposal for 50/50 gender equality in municipal certificates of appreciation and honor prizes. Agenda item only — vote outcome not visible.",
      quote_he: "הצעה לסדר מאת חבר המועצה, ניר קורן, שוויון מגדרי (5050) בתעודות ופרסי הוקרה",
      proposer: "ניר קורן, חבר המועצה",
      source_url: "https://www.givatayim.muni.il/protocols/"
    },
    {
      id: "givatayim-5",
      proposer_key: "kaplan",
      city: "GIVATAYIM",
      city_he: "גבעתיים",
      index: 267,
      date: "2022-02-08",
      document: "סדר יום, ישיבת מועצה מספר 49",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "agenda",
      outcome_he: "סעיף בסדר יום",
      summary_he: "הצעה שבחירת אמנים לאירועי יום העצמאות ואירועים עירוניים תייצג גיוון מגדרי. הצעה בלבד — תוצאת הצבעה לא נראית.",
      summary_en: "Proposal that artist selection for Independence Day and municipal events represent gender diversity. Agenda item only — vote outcome not visible.",
      quote_he: "בחירת האמנים תייצג גיוון מגדרי, תוך כדי שיתוף אמנים ואמניות תושבי.ות גבעתיים וגיל הזהב.",
      proposer: "רונאן קפלן, חבר המועצה",
      source_url: "https://www.givatayim.muni.il/protocols/"
    },

    // ═══ RAANANA (5 findings) ═══
    {
      id: "raanana-1",
      proposer_key: "meir",
      city: "RAANANA",
      city_he: "רעננה",
      index: 131,
      date: "2024-09-23",
      document: "פרוטוקול ועדת שמות",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "policy",
      outcome_he: "מדיניות פעילה",
      summary_he: "ועדת השמות אימצה מדיניות מפורשת של קריאת רחובות על שם נשים משמעותיות, מתוך \"קידום עקרונות שוויון מגדרי במרחב הציבורי\" ולצמצום הפער הקיים.",
      summary_en: "Names Committee adopted explicit policy of naming streets after significant women in Israeli history, framed as 'promoting principles of gender equality in the public space' and reducing the existing gap.",
      quote_he: "הוצג הרצון להמשיך החלטות קודמות בנושא זה ולשלב קריאת רחובות ע\"ש נשים משמעותיות בהיסטוריה הישראלית והמקומית, מתוך מקום ומדיניות של קידום עקרונות שוויון מגדרי במרחב הציבורי, ומתוך תכלית לפעול לצמצום הפער הקיים כיום.",
      proposer: "מירב מאיר, יו\"ר הוועדה",
      source_url: "https://www.raanana.muni.il/protocols/"
    },
    {
      id: "raanana-2",
      proposer_key: "meir",
      city: "RAANANA",
      city_he: "רעננה",
      index: 231,
      date: "2023-03-01",
      document: "הצעה לסדר — ייצוג הולם לנשים באירועים וכנסים עירוניים",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "proposal",
      outcome_he: "הצעה (ללא הצבעה נראית)",
      summary_he: "הצעה למספר שווה של נשים וגברים במציגים בכל אירוע בו העירייה שותפה במימונו, ולא לחתום הסכמים עם נותני שירותים המדירים נשים.",
      summary_en: "Proposal requiring equal numbers of women and men presenters at all municipally-funded events, and refusing contracts with service providers who exclude women.",
      quote_he: "מועצת העיר מחליטה בזאת כי בכל אירוע בו העירייה שותפה במימונו יהיה מספר שווה של נשים וגברים במציגים. מועצת העיר מחליטה כי לא ייחתמו הסכמים בין העירייה לבין נותני שירותים המדירים נשים משורותיהם.",
      proposer: "מירב מאיר (מרצ רעננה)",
      source_url: "https://www.raanana.muni.il/protocols/"
    },
    {
      id: "raanana-3",
      proposer_key: "meir",
      city: "RAANANA",
      city_he: "רעננה",
      index: 656,
      date: "2023-06-25",
      document: "הצעה לסדר — ייצוג הולם לנשים (הגשה מחודשת)",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "proposal",
      outcome_he: "הצעה (הגשה מחודשת)",
      summary_he: "הגשה מחודשת ומורחבת של הצעה לייצוג הולם לנשים, כעת מכסה גם שימוש במתקנים עירוניים (לא רק מימון ישיר).",
      summary_en: "Resubmission of women's representation proposal, now expanded to cover municipal facility use (not just direct funding).",
      quote_he: "מועצת העיר מחליטה בזאת כי בכל אירוע בו העירייה שותפה במימונו, גם אם לא מימון ישיר, אלא גם שימוש במתקן עירוני, יהיה מספר שווה של נשים וגברים במציגים ככל שניתן.",
      proposer: "מירב מאיר (מרצ רעננה)",
      source_url: "https://www.raanana.muni.il/protocols/"
    },
    {
      id: "raanana-4",
      proposer_key: "weintraub",
      city: "RAANANA",
      city_he: "רעננה",
      index: 767,
      date: "2022-12",
      document: "הצעה לסדר — הגנה על מערכת החינוך של רעננה",
      category: "education_program",
      category_he: "תוכנית חינוך",
      outcome: "proposal",
      outcome_he: "הצעה (ללא הצבעה נראית)",
      summary_he: "הצעה לתמוך בפעילות הסברה בבתי הספר לקידום זכויות קהילת הלהט\"ב, לממן תוכניות ברוח שוויון וסובלנות מכספי הרשות, ולשתף פעולה עם ארגון חוש\"ן.",
      summary_en: "Proposal to support LGBTQ+ rights advocacy in schools, fund equality/tolerance programs from municipal funds, and partner with CHOSHEN (LGBTQ+ education org).",
      quote_he: "מועצת העיר רעננה מתחייבת לתמוך במערכת החינוך [...] פעילות הסברה בבתי הספר לקידום זכויות קהילת הלהט\"ב [...] עיריית רעננה מתחייבת לממן מכספי הרשות תכניות ברוח זו של חופש מחשבתי, שוויון בין בני האדם [...] הסברה בתחום הגאווה והסובלנות — זכויות קהילת הלהט\"ב, מנהיגות נשים...",
      proposer: "רונית וינטראוב",
      source_url: "https://www.raanana.muni.il/protocols/"
    },
    {
      id: "raanana-5",
      proposer_key: "ayash",
      city: "RAANANA",
      city_he: "רעננה",
      index: 765,
      date: "2022-12",
      document: "הצעה לסדר — דיאלוג בין קהילות",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "proposal",
      outcome_he: "הצעה (ללא הצבעה נראית)",
      summary_he: "הצעה להקמת צוות היגוי בהובלת אגפי תרבות ואסטרטגיה לקידום דיאלוג בין קהילות בעיר, עם דיון בוועדת החינוך.",
      summary_en: "Proposal to establish a steering committee for inter-community dialogue, led by culture and strategy departments, with discussion in Education Committee.",
      quote_he: "מתבקשת המועצה לקבל החלטה על הקמת צוות היגוי וחשיבה בהובלת מנהלת אגף תרבות, מנהל אגף אסטרטגיה ומנהלים נוספים. לקידום צעדים מעשיים שיסייעו בחיבור בין הקהילות בעיר.",
      proposer: "לורן עייאש",
      source_url: "https://www.raanana.muni.il/protocols/"
    },

    // ═══ HOD HASHARON (1 finding) ═══
    {
      id: "hodhasharon-1",
      proposer_key: null,
      city: "HOD_HASHARON",
      city_he: "הוד השרון",
      index: 671,
      date: "2019-07-02",
      document: "פרוטוקול ישיבת מועצה מן המניין 12/19",
      category: "institutional_framework",
      category_he: "מסגרת מוסדית",
      outcome: "approved",
      outcome_he: "אושר",
      summary_he: "המועצה אישרה שינוי הרכב הוועדה לשוויון מגדרי, במסגרת שינויים ב-15 ועדות. עצם קיום הוועדה — מסגרת מוסדית מתמשכת.",
      summary_en: "Council approved composition change of the Gender Equality Committee, as part of 15 committee changes. The committee's existence itself confirms an ongoing institutional framework.",
      quote_he: "על סדר היום: ד. שינוי הרכב ועדות. 11. אישור שינוי הרכב הוועדה לשוויון מגדרי.",
      source_url: "https://www.hod-hasharon.muni.il/protocols/"
    }
  ]
,
  proposers: {
    lazimi: { name: "נעמה לזימי", city: "HAIFA", city_he: "חיפה", role: "חברת מועצת העירייה" },
    padlon: { name: "משה פדלון", city: "HERZLIYA", city_he: "הרצליה", role: "ראש העיר" },
    oren_yanai: { name: "דנה אורן ינאי", city: "HERZLIYA", city_he: "הרצליה", role: "חברת מועצה" },
    fabian: { name: "פביאן", city: "HERZLIYA", city_he: "הרצליה", role: "חבר מועצה" },
    kaplan: { name: "רונאן קפלן", city: "GIVATAYIM", city_he: "גבעתיים", role: "חבר מועצה" },
    wolfson: { name: "ויוי וולפסון", city: "GIVATAYIM", city_he: "גבעתיים", role: "חברת מועצה" },
    koren: { name: "ניר קורן", city: "GIVATAYIM", city_he: "גבעתיים", role: "חבר מועצה" },
    meir: { name: "מירב מאיר", city: "RAANANA", city_he: "רעננה", role: "חברת מועצה, מרצ רעננה" },
    weintraub: { name: "רונית וינטראוב", city: "RAANANA", city_he: "רעננה", role: "חברת מועצה" },
    ayash: { name: "לורן עייאש", city: "RAANANA", city_he: "רעננה", role: "חברת מועצה" }
  }
};